#!/usr/bin/env bash
# setup-api.sh — Interactive wizard to create the API proxy profile.
#
# Asks 2 questions (base_url + default model), generates
# ~/.codex/config.toml.profile.api, and pings the proxy to confirm it's
# reachable. API key is NOT handled here — Codex Desktop prompts for it
# in the GUI on first use and stores it in the macOS Keychain.
#
# Run directly:   bash setup-api.sh
# Or via install: bash install.sh   (installer offers to run the wizard)

set -euo pipefail

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
TARGET="$CODEX_HOME/config.toml.profile.api"

echo "==> codex-profile-switch: API profile setup wizard"
echo ""
echo "    This will create:  $TARGET"
echo ""
echo "    Note: This wizard does NOT ask for or store your API key."
echo "    Codex Desktop will prompt you for the key in its GUI on first use,"
echo "    and store it securely in the macOS Keychain."
echo ""

if [ ! -d "$CODEX_HOME" ]; then
    echo "❌ $CODEX_HOME doesn't exist. Install Codex Desktop and run it once first." >&2
    exit 1
fi

# ── Q1: base_url ─────────────────────────────────────────────────────────────
echo "Q1. API proxy base URL"
echo "    Examples:"
echo "      https://api.deepseek.com/v1"
echo "      https://openrouter.ai/api/v1"
echo "      https://your-proxy.example.com/v1"
echo "    (Must be an OpenAI-compatible /v1 endpoint.)"
read -r -p "    base_url: " BASE_URL
if [ -z "$BASE_URL" ]; then
    echo "❌ base_url is required." >&2
    exit 1
fi

# Normalize: strip trailing slashes
BASE_URL="${BASE_URL%/}"

# ── Q2: default model ────────────────────────────────────────────────────────
echo ""
echo "Q2. Default model name"
echo "    Examples: gpt-5.5, deepseek-chat, claude-sonnet-4, openrouter/auto"
echo "    Press Enter to use gpt-5.5 (works on most OpenAI-compatible relays)."
read -r -p "    model [gpt-5.5]: " MODEL
MODEL="${MODEL:-gpt-5.5}"

# ── Backup existing profile if present ──────────────────────────────────────
if [ -f "$TARGET" ]; then
    BACKUP="$TARGET.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$TARGET" "$BACKUP"
    echo ""
    echo "==> Existing profile backed up to: $BACKUP"
fi

# ── Generate profile ────────────────────────────────────────────────────────
echo ""
echo "==> Writing $TARGET"
cat > "$TARGET" <<EOF_PROFILE
# Generated by setup-api.sh on $(date +%Y-%m-%d)
# Re-run \`bash setup-api.sh\` to regenerate.

model_provider = "openai-custom"
model = "$MODEL"
model_reasoning_effort = "medium"

[model_providers.openai-custom]
name = "openai-custom"
base_url = "$BASE_URL"
wire_api = "responses"
requires_openai_auth = true
EOF_PROFILE
chmod 600 "$TARGET"
echo "    ✅ written (chmod 600)"

# ── Ping the proxy (unauthenticated, just checks reachability) ───────────────
echo ""
echo "==> Pinging $BASE_URL/models to verify host is reachable..."
if ! command -v curl > /dev/null; then
    echo "    ℹ️  curl not found — skipping connectivity check."
else
    HTTP_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
        --max-time 10 \
        "$BASE_URL/models" 2>/tmp/setup-api-probe-err.$$) || HTTP_CODE="000"

    case "$HTTP_CODE" in
        200) echo "    ✅ HTTP 200 — host reachable." ;;
        401|403) echo "    ✅ HTTP $HTTP_CODE — host reachable (auth required, expected for an unauthenticated probe)." ;;
        404) echo "    ⚠️  HTTP 404 — host reachable, but /v1/models doesn't exist. Double-check base_url ends in /v1." ;;
        000) echo "    ❌ Connection failed. base_url unreachable or DNS error."
             echo "       $(head -1 /tmp/setup-api-probe-err.$$ 2>/dev/null)" ;;
        *)   echo "    ℹ️  HTTP $HTTP_CODE — unusual response, but host responded. Verify with your relay's docs." ;;
    esac
    rm -f /tmp/setup-api-probe-err.$$
fi

# ── Final hints ─────────────────────────────────────────────────────────────
echo ""
echo "==> Done."
echo ""
echo "Next steps:"
echo "  1. Quit Codex Desktop completely (Cmd+Q, not just close window)"
echo "  2. Switch to API profile:"
echo "       bash switch.sh api"
echo "  3. Reopen Codex Desktop."
echo "  4. Codex will prompt you to paste your API key — have your sk-xxx key ready."
echo "     The key gets stored in the macOS Keychain, NOT in any config file."
echo "  5. Your full conversation history will still be there after switching."
echo ""
echo "To switch back:    bash switch.sh chatgpt"
echo "To re-run wizard:  bash setup-api.sh"


