#!/usr/bin/env bash
# setup-api.sh — Interactive wizard to create the API proxy profile.
#
# Asks 2 questions (base_url + default model), generates
# ~/.codex/config.toml.profile.api, and pings the proxy to confirm it's
# reachable. API key is NOT handled here — Codex Desktop prompts for it
# in the GUI on first use and stores it in the macOS Keychain.
#
# Run directly:   bash setup-api.sh
# Or via install: bash install.sh   (installer offers to run the wizard)

set -euo pipefail

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
TARGET="$CODEX_HOME/config.toml.profile.api"

echo "==> Codex Session Bridge: API profile setup wizard"
echo ""
echo "    This will create:  $TARGET"
echo ""
echo "    Note: This wizard does NOT ask for or store your API key."
echo "    Codex Desktop will prompt you for the key in its GUI on first use,"
echo "    and store it securely in the macOS Keychain."
echo ""

if [ ! -d "$CODEX_HOME" ]; then
    echo "❌ $CODEX_HOME doesn't exist. Install Codex Desktop and run it once first." >&2
    exit 1
fi

# ── Helper: ask yes/no with default, accept Chinese ─────────────────────────
ask_yn() {
    prompt="$1"; default="$2"
    if [ "$default" = "Y" ]; then suffix="[Y/n]"; else suffix="[y/N]"; fi
    printf '    %s %s ' "$prompt" "$suffix"
    read -r ans || ans=""
    [ -z "$ans" ] && { [ "$default" = "Y" ]; return; }
    case "$ans" in
        y|Y|yes|YES|Yes|是|要|好|好的|可以) return 0 ;;
        *) return 1 ;;
    esac
}

# ── Helper: probe base_url, returns 0 if usable, 1 if user wants to redo ────
probe_base_url() {
    url="$1"
    if ! command -v curl > /dev/null; then
        echo "    ℹ️  curl not found — skipping connectivity check."
        return 0
    fi
    echo ""
    echo "    探测 $url/models ..."
    HTTP_CODE=$(curl -sS -o /dev/null -w '%{http_code}' \
        --max-time 10 \
        "$url/models" 2>/tmp/setup-api-probe-err.$$) || HTTP_CODE="000"
    case "$HTTP_CODE" in
        200)
            echo "    ✅ HTTP 200 — 地址可用。"
            rm -f /tmp/setup-api-probe-err.$$
            return 0
            ;;
        401|403)
            echo "    ✅ HTTP $HTTP_CODE — 地址可用（需要鉴权，符合预期，API key 之后由 Codex 弹窗填）。"
            rm -f /tmp/setup-api-probe-err.$$
            return 0
            ;;
        404)
            echo "    ⚠️  HTTP 404 — 主机能连上，但 /v1/models 不存在。可能 base_url 没写到 /v1，或这家中转站不兼容 OpenAI /v1。"
            ;;
        000)
            echo "    ⚠️  连不上。可能是网络问题、地址拼错、少了 https:// 或 /v1。"
            err_msg=$(head -1 /tmp/setup-api-probe-err.$$ 2>/dev/null || true)
            [ -n "$err_msg" ] && echo "       $err_msg"
            ;;
        *)
            echo "    ℹ️  HTTP $HTTP_CODE — 不太常见的返回，主机有响应但不一定对。"
            ;;
    esac
    rm -f /tmp/setup-api-probe-err.$$
    echo ""
    if ask_yn "重新填 base_url？（选 N 表示「我就要这个地址，继续写文件」）" "Y"; then
        return 1
    fi
    return 0
}

# ── Q1: base_url（带探测 + 重试循环）────────────────────────────────────────
echo "Q1. API proxy base URL"
echo "    Examples:"
echo "      https://api.deepseek.com/v1"
echo "      https://openrouter.ai/api/v1"
echo "      https://your-proxy.example.com/v1"
echo "    (Must be an OpenAI-compatible /v1 endpoint.)"
while true; do
    read -r -p "    base_url: " BASE_URL
    if [ -z "$BASE_URL" ]; then
        echo "❌ base_url is required." >&2
        continue
    fi
    BASE_URL="${BASE_URL%/}"
    if probe_base_url "$BASE_URL"; then
        break
    fi
done

# ── Q2: default model（必填，不同中转站名字不一样，没有通用默认值）──────────
echo ""
echo "Q2. Default model name"
echo "    必须填一个这家中转站支持的模型名，不同中转站名字不一样。"
echo "    Examples:"
echo "      DeepSeek:    deepseek-chat / deepseek-reasoner"
echo "      OpenRouter:  openrouter/auto / anthropic/claude-sonnet-4"
echo "      OpenAI 兼容: gpt-4o / gpt-4o-mini / gpt-4-turbo"
echo "    填错了 Codex 起来会报 model not found，回来重跑 setup-api.sh 即可。"
while true; do
    read -r -p "    model: " MODEL
    if [ -n "$MODEL" ]; then break; fi
    echo "    ❌ 模型名不能空。"
done

# ── Backup existing profile if present ──────────────────────────────────────
if [ -f "$TARGET" ]; then
    BACKUP="$TARGET.bak.$(date +%Y%m%d_%H%M%S)"
    cp "$TARGET" "$BACKUP"
    echo ""
    echo "==> Existing profile backed up to: $BACKUP"
fi

# ── Generate profile ────────────────────────────────────────────────────────
echo ""
echo "==> Writing $TARGET"
cat > "$TARGET" <<EOF_PROFILE
# Generated by setup-api.sh on $(date +%Y-%m-%d)
# Re-run \`bash setup-api.sh\` to regenerate.

model_provider = "openai-custom"
model = "$MODEL"
model_reasoning_effort = "medium"

[model_providers.openai-custom]
name = "openai-custom"
base_url = "$BASE_URL"
wire_api = "responses"
requires_openai_auth = true
EOF_PROFILE
chmod 600 "$TARGET"
echo "    ✅ written (chmod 600)"

# ── Final hints ─────────────────────────────────────────────────────────────
echo ""
echo "==> Done."
echo ""
echo "Next steps:"
echo "  1. Quit Codex Desktop completely (Cmd+Q, not just close window)"
echo "  2. Bridge to API profile:"
echo "       bash switch.sh api"
echo "  3. Reopen Codex Desktop."
echo "  4. Codex will prompt you to paste your API key — have your sk-xxx key ready."
echo "     The key gets stored in the macOS Keychain, NOT in any config file."
echo "  5. Your full conversation history will still be visible after bridging."
echo ""
echo "To bridge back:    bash switch.sh chatgpt"
echo "To re-run wizard:  bash setup-api.sh"


